using KernelDensity
using PyPlot

# This script relies on data (emu_out, sim_out) that is generated by running smc-abc-script.jl

ion()
fig = figure(figsize=(15,15))
ioff()
grid_size = size(emu_out.population[3], 2)
emu_handle = nothing
sim_handle = nothing
for i in 1:grid_size
    for j in 1:grid_size
        if j < i
            subplot2grid((grid_size, grid_size), (i - 1, j - 1))
            x_data = emu_out.population[3][:,i]
            y_data = emu_out.population[3][:,j]
            kde_joint = kde(hcat(x_data, y_data))
            contour_x = linspace(extrema(x_data)..., 100)
            contour_y = linspace(extrema(y_data)..., 100)
            contour_z = pdf(kde_joint, contour_x, contour_y)
            contour(contour_x, contour_y, contour_z, colors="salmon")
            scatter(sim_out.population[3][:,i], sim_out.population[3][:,j], marker="x", color="cornflowerblue")
            xlabel("Parameter $i")
            ylabel("Parameter $j")
        elseif i == j
            subplot2grid((grid_size, grid_size), (i - 1, j - 1))
            emu_data = emu_out.population[3][:,i]
            sim_data = sim_out.population[3][:,i]
            kde_emu = kde(emu_data)
            kde_sim = kde(sim_data)
            x_emu_plot = linspace(extrema(emu_data)..., 100)
            y_emu_plot = pdf(kde_emu,x_emu_plot)
            x_sim_plot = linspace(extrema(sim_data)..., 100)
            y_sim_plot = pdf(kde_sim,x_sim_plot)
            emu_handle = plot(x_emu_plot, y_emu_plot, color="salmon")
            sim_handle = plot(x_sim_plot, y_sim_plot, color="cornflowerblue")
            xlabel("Parameter $i")
            yticks([])
        end
    end
end
if grid_size > 1
    subplot2grid((grid_size, grid_size), (0, 1))
    legend([emu_handle; sim_handle], ["Emulation", "Simulation"], loc="upper left")
    axis("off")
else
    figlegend([emu_handle; sim_handle], ["Emulation", "Simulation"], loc="upper right")
end
subplots_adjust(
left    =  0.08,
bottom  =  0.06,
right   =  0.96,
top     =  0.97,
wspace  =  0.26,
hspace  =  0.26)
show(fig)
# savefig("/project/home17/et517/Desktop/gpabc-figure-emu-sim.pdf")
